[package]
name = "multitest"
version = "0.0.1"
authors = ["Dariusz Depta <DariuszDepta@users.noreply.github.com>"]
description = "Work in progress"
repository = "https://github.com/DariuszDepta/multitest.git"
license = "Apache-2.0"
edition = "2021"
